# numpy
* [https://numpy.org/devdocs/user/quickstart.html](https://numpy.org/devdocs/user/quickstart.html)
* numpy: Numerical Python 과학적, 산업적 연산을 위한 패키지
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* python list와의 차이: 자료형이 1가지만 들어간다.
* 우선순위 int < float < str

# 차원
* 0 차원 = 점 . 스칼라  a = 10
* 1 차원 = 선 --- 방향이 없는 벡터, 배열, list, tuple  [1, 2, 3, 4]
* 2 차원 = 면(가로, 세로) - DB 테이블, DataFrame, excel Sheet, matrix, 행렬
* 3 차원 = 입체(가로, 세로, 깊이), 정육면체(주사위), 2차원 데이터의 묶음 - excel file
* 4 차원 = 3차원 데이터의 묶음
* 5 차원 = 4차원 데이터의 묶음

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
num = 10

* 차원을 출력하는 메서드 .ndim
* 차원의 형태를 출력하는 메서드 .shape

In [4]:
num.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [7]:
# ndarray는 벡터이므로 1차원
a.ndim

1

In [8]:
# ndarray는 방향이 없는 벡터
a.shape

(5,)

In [11]:
# 세로로 방향을 가진 열벡터 -> 방향이 생기면 2차원이 됨
a2 = np.array([[1], [2], [3], [4], [5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
# 앞이 행, 뒤가 열
a2.shape

(5, 1)

In [13]:
a2.ndim

2

In [14]:
# 행이 한 개고 열이 여러개인 행벡터
a3 = np.array([[1,2,3,4,5]])
a3

array([[1, 2, 3, 4, 5]])

In [15]:
a3.ndim

2

In [16]:
a3.shape

(1, 5)

# 2차원 데이터

In [17]:
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
print(d2.ndim, d2.shape)

2 (2, 5)


# 3차원 데이터

In [20]:
d3 = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]])
d3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [21]:
print(d3.ndim, d3.shape)

3 (4, 2, 5)


# 4차원 데이터

In [22]:
d4 = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
              [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]])
d4

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [23]:
print(d4.ndim, d4.shape)

4 (2, 4, 2, 5)


# 5차원 데이터

In [57]:
d5 = np.array([[[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
              [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]],
              [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
              [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]])
d5

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

  

In [58]:
print(d5.ndim, d5.shape)

5 (2, 2, 4, 2, 5)


In [26]:
l5 = [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
              [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
               [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]
l5

[[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]],
 [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]]]

# Numpy를 사용해야 하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [28]:
# 0차원 스칼라 연산
a = 10
b = 5
scalar = a + b
scalar

15

In [29]:
scalar + 10

25

In [30]:
# 1차원 벡터의 연산
v1 = [1,2,3,4,5]
# v1의 요소에 10을 곱한 리스트를 만드세요.
v1 * 10

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [31]:
# v1의 요소에 10을 곱한 리스트를 만드세요.
mul10 = []
for num in v1:
    mul10.append(num * 10)
mul10

[10, 20, 30, 40, 50]

In [32]:
mul10 = [num * 10 for num in v1]
mul10

[10, 20, 30, 40, 50]

In [33]:
# 2차원 데이터 연산 10 곱해서 출력
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
for l1 in d2:
    print(l1)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [43]:
for l1 in d2:
    for num in l1:
        print(num)

1
2
3
4
5
6
7
8
9
10


In [42]:
for l1 in d2:
    for num in l1:
        print(num * 10)

10
20
30
40
50
60
70
80
90
100


In [41]:
result = []
for l1 in d2:
    temp = []
    for num in l1:
        temp.append(num * 10)
    result.append(temp)
result

[[np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)],
 [np.int64(60), np.int64(70), np.int64(80), np.int64(90), np.int64(100)]]

In [44]:
# 3차원 데이터에 10 곱하는 연산

In [45]:
for item1 in d3:
    print(item1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [46]:
for item1 in d3:
    for item2 in item1:
        print(item2)

[1 2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [47]:
for item1 in d3:
    for item2 in item1:
        for item3 in item2:
            print(item3)

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [52]:
result3 = []
for item1 in d3:
    temp2 = []
    for item2 in item1:
        temp1 = []
        for item3 in item2:
            temp1.append(item3 * 10)
        temp2.append(temp1)
    result3.append(temp2)
result3 = np.array(result3)
print(result3, "\n", result3.ndim, result3.shape)

[[[ 10  20  30  40  50]
  [ 60  70  80  90 100]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]] 
 3 (4, 2, 5)


In [53]:
d4 * 10

array([[[[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],

        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],

        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],

        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]]],


       [[[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],

        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],

        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],

        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]]]])

# numpy에서 자주 사용하는 메서드
* .ndim : 몇 차원인지 확인
* .shape : 몇 차원, 몇행, 몇열인지 구조 확인
* .size : 배열 안에 있는 요소의 총 개수가 몇 개인지
* .dtype : 데이터 타입이 무엇인지

In [59]:
d5

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

  

In [60]:
print(d5.ndim, d5.shape, d5.size, d5.dtype)

5 (2, 2, 4, 2, 5) 160 int64


# ndarray 만들기
* numpy의 기본 자료형 ndarray
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [62]:
e1 = np.array([1,2,3,4,5])
e1

array([1, 2, 3, 4, 5])

In [63]:
e2 = np.array((1,2,3,4,5))
e2

array([1, 2, 3, 4, 5])

In [65]:
e3 = np.array((1,2,3.0,4,5))
print(e3, e3.dtype)

[1. 2. 3. 4. 5.] float64


In [66]:
e4 = np.array((1,2,3.0,"4",5))
print(e4, e4.dtype)

['1' '2' '3.0' '4' '5'] <U32


# np.arange(시작, 끝, step)

In [67]:
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

In [69]:
a2 = np.arange(11, 1, -3)
a2

array([11,  8,  5,  2])

In [70]:
# 1-100까지 있는 array
a3 = np.arange(1, 101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# .reshape(행, 열)
* 벡터를 원하는 크기의 다차원 배열로 변환

In [71]:
print(a3.ndim, a3.shape)

1 (100,)


In [73]:
a4 = a3.reshape(20, 5)
print(a4.ndim, a4.shape)
a4

2 (20, 5)


array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [74]:
a4 = a3.reshape(5, 2, 2, 5)
print(a4.ndim, a4.shape)
a4

4 (5, 2, 2, 5)


array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10]],

        [[ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]]],


       [[[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]]],


       [[[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70]],

        [[ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]]],


       [[[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])

In [76]:
a5 = a3.reshape(-1, 1, 2, 2, 5)
print(a5.ndim, a5.shape)
a5

5 (5, 1, 2, 2, 5)


array([[[[[  1,   2,   3,   4,   5],
          [  6,   7,   8,   9,  10]],

         [[ 11,  12,  13,  14,  15],
          [ 16,  17,  18,  19,  20]]]],



       [[[[ 21,  22,  23,  24,  25],
          [ 26,  27,  28,  29,  30]],

         [[ 31,  32,  33,  34,  35],
          [ 36,  37,  38,  39,  40]]]],



       [[[[ 41,  42,  43,  44,  45],
          [ 46,  47,  48,  49,  50]],

         [[ 51,  52,  53,  54,  55],
          [ 56,  57,  58,  59,  60]]]],



       [[[[ 61,  62,  63,  64,  65],
          [ 66,  67,  68,  69,  70]],

         [[ 71,  72,  73,  74,  75],
          [ 76,  77,  78,  79,  80]]]],



       [[[[ 81,  82,  83,  84,  85],
          [ 86,  87,  88,  89,  90]],

         [[ 91,  92,  93,  94,  95],
          [ 96,  97,  98,  99, 100]]]]])

# flatten()
* 다차원 배열을 1차원으로 펼쳐줌

In [77]:
a4.ndim

4

2/2 강의 1:54:08